# Generated by Django 5.2.8 on 2025-11-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('book_type', models.CharField(max_length=30)),
                ('page_no', models.IntegerField(max_length=30)),
                ('added_date', models.DateField()),
                ('publish_date', models.DateField()),
            ],
        ),
    ]
