# Generated by Django 5.2.8 on 2025-11-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_alter_library_added_date_alter_library_page_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='library',
            name='book_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='library',
            name='book_type',
            field=models.CharField(max_length=100),
        ),
    ]
